export const metadata = { title: "About — PCFit" };

export default function About() {
  return (
    <main className="container page">
      <h1>About PCFit</h1>
      <p>
        Every day, thousands of people post the same question online: "I have a budget and I know
        what games I want to play — what should I buy?" Compatibility tools answer a different
        question. They check whether the parts you already chose fit together, which is great —
        once you've chosen. PCFit exists for the step before that.
      </p>
      <p>
        Tell PCFit your budget, your games, and your goals, and it produces a complete, balanced
        parts list with plain-English reasons for every choice. It allocates your money the way
        experienced builders do — prioritizing the GPU for gaming builds, avoiding bottlenecks,
        and leaving sensible headroom in the power supply.
      </p>
      <h2>How recommendations work</h2>
      <p>
        Builds are generated by AI (Anthropic's Claude) using your answers. Prices are estimates of
        typical US street prices and change daily, so always confirm current prices and exact model
        compatibility on the retailer's page before buying. PCFit is a starting point that saves
        you hours of research — not a replacement for double-checking a final cart.
      </p>
      <h2>How PCFit makes money</h2>
      <p>
        PCFit is free to use. When you buy parts through links on this site, we may earn a small
        affiliate commission from retailers like Amazon at no extra cost to you. This never
        influences which parts the AI recommends. Read our full{" "}
        <a href="/disclosure">affiliate disclosure</a>.
      </p>
    </main>
  );
}
